const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');
const db = require('../database');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('sales')
    .setDescription('Track sales stats and leaderboards')
    .addSubcommand(subcommand =>
      subcommand.setName('stats')
        .setDescription('Show total sales and sales statistics')
    )
    .addSubcommand(subcommand =>
      subcommand.setName('user')
        .setDescription('Show sales generated by a specific staff member')
        .addUserOption(option =>
          option.setName('user')
            .setDescription('The staff member to search')
            .setRequired(true)
        )
    )
    .addSubcommand(subcommand =>
      subcommand.setName('leaderboard')
        .setDescription('Show leaderboard of staff members by successful sales')
    ),

  async execute(interaction, config) {
    const subcommand = interaction.options.getSubcommand();
    const guild = interaction.guild;

    if (!guild) {
      return interaction.reply({ content: '❌ This command can only be used inside a Discord server.', ephemeral: true });
    }

    await interaction.deferReply();

    // ==========================================
    // 1. SALES STATS (GLOBAL SUMMARY)
    // ==========================================
    if (subcommand === 'stats') {
      try {
        const stats = await db.getSalesStats();

        const statsEmbed = new EmbedBuilder()
          .setTitle('💰 Pavo Tweak Sales Dashboard')
          .setColor(config.embedColor || '#4f46e5')
          .setThumbnail(guild.iconURL({ dynamic: true }) || null)
          .addFields(
            { name: '📊 Total Sales Count', value: `\`${stats.count}\` transactions`, inline: true },
            { name: '💵 Gross Revenue', value: `**$${stats.revenue.toFixed(2)}**`, inline: true },
            { name: '📈 Paid Commission', value: `**$${stats.commissions.toFixed(2)}**`, inline: true }
          )
          .setTimestamp();

        // Breakdown by Payment Method
        if (stats.byMethod && stats.byMethod.length > 0) {
          const breakdownStr = stats.byMethod.map(m => 
            `• **${m.payment_method}**: \`${m.count}\` sales ($${m.revenue.toFixed(2)} revenue)`
          ).join('\n');
          statsEmbed.addFields({ name: '💳 Payment Methods Breakdown', value: breakdownStr, inline: false });
        } else {
          statsEmbed.addFields({ name: '💳 Payment Methods Breakdown', value: 'No payment methods recorded yet.', inline: false });
        }

        await interaction.editReply({ embeds: [statsEmbed] });
      } catch (err) {
        console.error('Error fetching sales stats:', err);
        await interaction.editReply({ content: `❌ Error fetching sales stats: ${err.message}` });
      }
    }

    // ==========================================
    // 2. SALES USER (STAFF SPECIFIC)
    // ==========================================
    else if (subcommand === 'user') {
      const targetUser = interaction.options.getUser('user');

      try {
        const stats = await db.getSalesByUser(targetUser.id);

        const userEmbed = new EmbedBuilder()
          .setTitle(`📈 Sales Report: ${targetUser.username}`)
          .setColor(config.embedColor || '#4f46e5')
          .setThumbnail(targetUser.displayAvatarURL({ dynamic: true }) || null)
          .addFields(
            { name: '👤 Staff Member', value: `<@${targetUser.id}> (\`${targetUser.id}\`)`, inline: false },
            { name: '📊 Sales Logged', value: `\`${stats.count}\``, inline: true },
            { name: '💵 Revenue Generated', value: `**$${stats.revenue.toFixed(2)}**`, inline: true },
            { name: '📈 Total Commission', value: `**$${stats.commission.toFixed(2)}**`, inline: true }
          )
          .setTimestamp();

        // List recent sales
        if (stats.recent && stats.recent.length > 0) {
          const recentList = stats.recent.map((s, idx) => {
            const dateStr = s.date.split('T')[0];
            return `\`#${idx + 1}\` **${s.product}** - $${s.price.toFixed(2)} via *${s.payment_method}* to **${s.customer_username}** on *${dateStr}* (Earned: $${s.commission.toFixed(2)})`;
          }).join('\n');
          userEmbed.addFields({ name: '📋 Recent Recorded Sales (Max 10)', value: recentList, inline: false });
        } else {
          userEmbed.addFields({ name: '📋 Recent Recorded Sales', value: 'No sales recorded for this staff member yet.', inline: false });
        }

        await interaction.editReply({ embeds: [userEmbed] });
      } catch (err) {
        console.error('Error fetching sales by user:', err);
        await interaction.editReply({ content: `❌ Error fetching user sales: ${err.message}` });
      }
    }

    // ==========================================
    // 3. SALES LEADERBOARD
    // ==========================================
    else if (subcommand === 'leaderboard') {
      try {
        const leaderboard = await db.getSalesLeaderboard();

        const leaderboardEmbed = new EmbedBuilder()
          .setTitle('🏆 Pavo Tweak Staff Sales Leaderboard')
          .setDescription('Staff members ranked by successful manual sales recorded.')
          .setColor(config.embedColor || '#4f46e5')
          .setThumbnail(guild.iconURL({ dynamic: true }) || null)
          .setTimestamp();

        if (leaderboard && leaderboard.length > 0) {
          const rows = leaderboard.map((row, index) => {
            let medal = '•';
            if (index === 0) medal = '🥇';
            else if (index === 1) medal = '🥈';
            else if (index === 2) medal = '🥉';

            return `${medal} **Rank #${index + 1}** | <@${row.staff_id}> (${row.username || 'Unknown'}) - **${row.sales_count}** sales ($${row.revenue.toFixed(2)} total revenue)`;
          }).join('\n');
          
          leaderboardEmbed.setDescription(rows);
        } else {
          leaderboardEmbed.setDescription('⚠️ No sales records found. Sales stats will show up here once recorded.');
        }

        await interaction.editReply({ embeds: [leaderboardEmbed] });
      } catch (err) {
        console.error('Error fetching leaderboard:', err);
        await interaction.editReply({ content: `❌ Error fetching sales leaderboard: ${err.message}` });
      }
    }
  }
};
